spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\Ns\workSpaces\IdeaProjects\mqr\db\mqr.db?date_string_format=yyyy-MM-dd HH:mm:ss
    username:
    password:

# 日志级别
logging:
  level:
    com:
      molicloud:
        mqr: debug
  file:
    path: C:\Ns\workSpaces\IdeaProjects\mqr\logs\
    name: C:\Ns\workSpaces\IdeaProjects\mqr\logs\mqr.log
    max-history: 60